### PR TITLE
Update for solidus 4

### PR DESCRIPTION
**Pull request by AlistairNorman**
I just updated a couple things to get this ready for Solidus 4. I have an app on Solidus 4 that I want to use this on. Let me know if you see anything else that needs to be done.

### CODE REVIEW

**Review by forkata — APPROVED** [review]
Nice work here @AlistairNorman 🚀

**Comment by forkata** [comment]
@AlistairNorman It looks like we're going to need to update the Circle.Ci configuration to switch to Ruby 3

**Comment by AlistairNorman** [comment]
Looks like there are some version related failures on the tests. I'll fix that up next week.

**Comment by forkata** [comment]
@kennyadsl It looks like there is no `solidus_frontend` v4.1 branch, so the specs for that version fail to bundle. Is the expectation that repo follows the main gem's versioning? If not we can update the `Gemfile` to lock `solidus_frontend` at v4.0.

**Comment by kennyadsl** [comment]
cc @elia was this part of the release process?

**Comment by elia** [comment]
I think `solidus_frontend` dependency on core is now very loose, and the last version that was released in lockstep with solidus was 3.4, after that the version numbers are no longer connected.

I'm ensuring specs pass with the latest 4.2 release, but could really use some help since the gem is no longer actively maintained, and would probably make sense to move it under @solidusio-contrib at this point.

If anyone is willing to take up the challenge please let me know (so we don't duplicate work), I'm happy to help with reviews, merges, and releases.

**Comment by AlistairNorman** [comment]
@elia @kennyadsl I fixed up the issues with running against the various Solidus versions. Can we merge this?

**Review by kennyadsl — APPROVED** [review]
Thanks!

**Pull request merged**
